os:
    - linux
    - osx

language: go

go:
    - 1.9.2

install: true

script:
    - make deps
    - gx-go rewrite
    - go test -v -race -coverprofile=unittest.coverprofile -covermode=atomic .


after_success:
    - bash <(curl -s https://codecov.io/bash) -f unittest.coverprofile -F unittest

cache:
    directories:
        - $GOPATH/src/gx
